default:
  tags:
    - docker

stages:
  - deploy
pages:
  image: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/jekyll
  stage: deploy
  artifacts:
    paths:
      - public
  publish: public
  only:
    - master
  script:
    - bundle install
    - bundle exec jekyll build --baseurl /docs/ -d public/
