default:
  tags:
    - docker

stages:
  - deploy
pages:
  image: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/jekyll
  stage: deploy
  artifacts:
    paths:
      - public
  publish: public
  only:
    - master
  script:
    - echo url: https://invoicebox.gitlab.invbox.ru > _config_internal.yml
    - bundle install
    - bundle exec jekyll build --baseurl /docs/ --config _config.yml,_config_internal.yml -d public/
